### ISSUE TITLE
s/RECORDS/DOCUMENTS

### ISSUE THREAD

**Issue by travissarles** [scalacenter/scala.epfl.ch#3]
A record is "a thing constituting a piece of evidence about the past, especially an account kept in writing or some other permanent form."

This is not the case with membership regulations/agreement.

**Comment by heathermiller** [comment]
Well, the records are the minutes (which are records) and then the membership documents. I actually just went with what other open source foundations call this page. They all seem to call it "Records" 🤷‍♀️
